mysite/myapp/urls.py
from django.urls import path
from myapp.views import index, indexItem, add_item, update_item, delete_item

app_name = "myapp"

urlpatterns = [
    #http://127.0.0.1:8000/myapp/
    path('', index, name='index'),
    path('<int:my_id>/', indexItem, name="detail"),
    #http://127.0.0.1:8000/myapp/
    path('additem/', add_item, name="add_item"),
    path('updateitem/<int:my_id>/', update_item, name="update_item"),
    path('deleteitem/<int:my_id>/', delete_item, name="delete_item"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("myapp/", include("myapp.urls", namespace="myapp")),
    path("users/", include("users.urls", namespace="users")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.urls import path
from .views import register

app_name = "users"

urlpatterns = [
    #http://127.0.0.1:8000/users/
    path('register/', register, name='register'),
]

mysite/myapp/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length = 100)
    price = models.IntegerField()
    description = models.CharField(max_length = 200)
    image = models.ImageField(blank=True, upload_to='images')

    def __str__(self):
        return self.name

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, upload_to='_profile_images')
    contact_number = models.CharField(max_length=50, default="+7928123456789")

    def __str__(self):
        return self.user.username

mysite/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class NewUserForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={"class": "focus:outline-none", "placeholder": "mail@mail.com"}
        ),
    )
    username = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={"class": "focus:outline-none", "placeholder": "Enter username..."}
        ),
    )
    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={"class": "focus:outline-none", "placeholder": "Enter password"}
        ),
    )
    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={"class": "focus:outline-none", "placeholder": "Enter same password"}
        ),
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

mysite/myapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Product

def index(request):
    items = Product.objects.all()
    context = {
        'items':items
    }
    return render(request, "myapp/index.html", context)

def indexItem(request, my_id):
    item = Product.objects.get(id=my_id)
    context = {'item':item}
    return render(request, "myapp/detail.html", context=context)

def add_item(request):
    if request.method == "POST":
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        image = request.FILES['upload']
        item = Product(name=name, price=price, description=description, image=image)
        item.save()
    return render(request,"myapp/additem.html")

def update_item(request, my_id):
    item = Product.objects.get(id=my_id)
    if request.method == "POST":
        item.name = request.POST.get("name")
        item.price = request.POST.get("price")
        item.description = request.POST.get("description")
        item.image = request.FILES.get('upload', item.image)
        item.save()
        return redirect("/myapp/")
    context = {'item':item}
    return render(request, "myapp/updateitem.html", context)

def delete_item(request, my_id):
    item = Product.objects.get(id=my_id)
    if request.method == "POST":
        item.delete()
        return redirect("/myapp/")
    context = {'item':item}
    return render(request, "myapp/deleteitem.html", context)

mysite/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from .forms import NewUserForm

def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
    form = NewUserForm()
    context = {'form': form}
    return render(request, 'users/register.html', context)

mysite/myapp/templates/myapp/additem.html
{% extends "myapp/base.html" %}

{% block content %}
<div class="ml-[200px]">
    <h1 class="text-2xl m-10 font-bold text-green-600"> Додайте новий елемент нижче</h1>
    <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8 " method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="mb-4 ">
            <label class="block text-gray-700 text-md font-bold mb-2" for="name">Назва</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Назва..." name="name" id="name">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price">Ціна</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Ціна..." name="price" id="price">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="description">Опис</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Опис..." name="description" id="description">
            <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload">
            <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Add Item" value="Add Item">Додати</button>
        </div>
    </form>
</div>

{% endblock content %}

mysite/myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
    <title>Document</title>
</head>
<body>
    {% include "myapp/navbar.html" %}
    {% block content %}
            TEXT
    {% endblock content %}
</body>
</html>

mysite/myapp/templates/myapp/deleteitem.html
{% extends "myapp/base.html" %}

{% block content %}
    <h1 class="text-2xl m-10 font-bold">Видалити продукт</h1>
    <form class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4" method="post">
        {% csrf_token %}
        <div class="mb-4">
            <label class="block text-gray text-sm font mb-2">Ти впевнений, що хочеш видалити цей продукт? </label>
            <label class="block text-gray text-sm font mb-2"> {{ item.name }} </label>
            <img class="w-40 h-40" src="{{ item.image.url }}" alt="" srcset="">
        </div>
        <button class="block bg-green-600 text-white p-3 mt-4" type="submit" value="Підтвердити">Підтвердити</button>
    </form>

{% endblock content %}

mysite/myapp/templates/myapp/detail.html
{% extends "myapp/base.html" %}
{% load humanize %}

{% block content %}
<div class="flex p-10 w-full h-200">
    <img class="w-1/3" src="{{ item.image.url }}" alt="itemPhoto">
    <div class="w-2/3 text-xl ml-10 mt-5">
        <p class="mt-5">{{ item.name }}</p>
        <p class="mt-5 text-green-500">$ {{ item.price | intcomma }}</p>
        <p class="mt-5 text-gray-600">{{ item.description }}</p>
        <button class="block bg-green-600 text-white p-3 mt-4"><a href="{% url 'myapp:update_item' item.id %}">Оновити елемент</a></button>
        <button class="block bg-green-600 p-3 mt-4"><a href="{% url 'myapp:delete_item' item.id %}">Видалити елемент</a></button>
    </div>
</div>
{% endblock content %}

mysite/myapp/templates/myapp/index.html
{% extends "myapp/base.html" %}

{% block content %}
<main class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:my-28">
<div class="sm:text-center lg:text-left">
    <h1 class="text-4xl font-extrabold text-gray-900 sm:text-Sxl md:text-6xl">
        <span class="block xl:inline">Ексклюзивні товари</span>
        <span class="block xl:inline text-red-500">По Супер Цінам</span>
    </h1>
    <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">Ви можете замовити товар з будь-якої точки світу. Доставка включена.</p>
</div>
<div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-col-3 lg:grid-col-3 gap-3">
    {% for item in items %}
    <a href="{% url 'myapp:detail' item.id %}">
        <div class="rounded overflow-hidden shadow-lg">
            <img class="w-full h-[400px]" src="{{item.image.url}}" alt="">
            <div class="px-6 py-4">
                <p class="font-bold text-xl mb-2">{{item.name}}</p>
                <p class="font-bold text-xl text-green-500 mb-2">$ {{item.price}}</p>
                <p class="text-green-700 text-base">{{ item.description }}</p>
            </div>
        </div>
    </a>
    {% endfor %}
</div>
</main>

{% endblock content %}

mysite/myapp/templates/myapp/navbar.html
{% load static %}
<nav class="bg-white shadow-lg">
    <div class="max-w-6xl mx-auto px-4">
        <div class="flex justify-between">
            <div class="flex space-x-7">
                <div>
                    <a href="#" class="flex item-center px-2 py-4">
                    <img class="h-8 w-8" src="{% static 'myapp/images/logo.png' %}" alt="logo" />
                    <span class="text-gray-500 font-bold text-xl">Elec Shop</span>
                </a>
                </div>
                <div class="items-center flex space-x-1">
                    <a href="#" class="py-4 px-2 text-gray-500 font-bold border-b-4 border-red-500">Home</a>
                    <a href="#" class="py-4 px-2 text-gray-500 font-bold">About</a>
                    <a href="#" class="py-4 px-2 text-gray-500 font-bold">Contacts</a>
                    <a href="#" class="py-4 px-2 text-gray-500 font-bold">Place</a>
                </div>
            </div>
        </div>
    </div>
</nav>

mysite/myapp/templates/myapp/updateitem.html
{% extends "myapp/base.html" %}

{% block content %}
<div class="ml-[200px]">
    <h1 class="text-2xl m-10 font-bold text-green-600"> Оновити новий елемент</h1>
    <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8 " method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="mb-4 ">
            <label class="block text-gray-700 text-md font-bold mb-2" for="name">Назва</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{ item.name }}" type="text" placeholder="Назва..." name="name" id="name">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price">Ціна</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{ item.price }}" type="text" placeholder="Ціна..." name="price" id="price">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="description">Опис</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{ item.description }}" type="text" placeholder="Опис..." name="description" id="description">
            <img class="w-20 h-20" src="{{ item.image.url }}" alt="" srcset="">
            <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload">
            <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Add Item" value="Add Item">Оновити елемент</button>
        </div>
    </form>
</div>

{% endblock content %}

mysite/users/templates/users/register.html
{% extends "myapp/base.html" %}

{% block content %}
    <div class="container py-5">
        <h1 class="text-2xl m-10 font-bold">Реєстрація</h1>
        <form class="w-2/5 bg-white-700 shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4" method="post">
            {% csrf_token %}
            <div class="mb-2">
                <label class="block text-gray-700 text-sm font-bold mb-2">Username</label>
                <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{form.username}}</p>
                <label class="block text-gray-700 text-sm font-bold mt-5 mb-2">Email</label>
                <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{form.email}}</p>
                <label class="block text-gray-700 text-sm font-bold mt-5 mb-2">Password</label>
                <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{form.password1}}</p>
                <label class="block text-gray-700 text-sm font-bold mt-5 mb-2">Confirm Password</label>
                <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{form.password2}}</p>
            </div>
            <button class="block bg-green-600 text-white p-3 mt-4" type="submit">Register</button>
        </form>
    </div>

{% endblock content %}